services:
  mysql:
    image: mysql:8.4
    container_name: nutrion_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nutrion_db
      MYSQL_USER: nutrion_user
      MYSQL_PASSWORD: nutrion_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
